### ISSUE TITLE
Creating a Native iOS or Android UI

### ISSUE THREAD

**Issue by Jonatthu** [karpikpl/identity-server4-with-SPA-UI#2]
I looked this repo and everything make sense but how about a native UI?
We can not use iframes, how this project would change?

**Comment by karpikpl** [comment]
I haven't worked on native apps, but from what I understand, the flow is pretty much the same, just instead of web redirects, you want to have myapp:// redirects.

see: https://auth0.com/docs/flows/concepts/auth-code-pkce

**Comment by karpikpl** [comment]
I'm closing since I don't have plans on expanding this little project
