### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by mesutpiskin** [karpikpl/identity-server4-with-SPA-UI#3]
I'm using Identity Server 4 and Dotnet Core Identity for authentication service. Authentication service has custom react spa.

I'm trying to get started a authenticate a user using their mobile number. I have a user data (email, password, phone number, etc.) I want this steps;

- User:Key in email and password (done)
- Server:Send sms with code to mobile number (?), i have a sms server
- User:Key-in code from SMS
- Server:Send access token (done)

I have no idea how to integrate two factors, how can I help you? 
Thank you.

**Comment by karpikpl** [comment]
So the way I would do it is:
- when the SPA sends username/password to the server, generate a short lived, server-encrypted 2-3min MFA cookie. Do not issue IS4 cookie yet
- make the user do the second factor
- on the server validate second factor and the MFA cookie, Authenticate the user
