### ISSUE TITLE
Update demo

### ISSUE THREAD

**Issue by sergeyshaykhullin** [karpikpl/identity-server4-with-SPA-UI#7]
I have some problems with running this demo

One of them is that `login-spa` is not logging in, may be it is of old oidc-client, because i am getting no logs from it
Network activity `.har` file: [localhost.zip](https://github.com/karpikpl/identity-server4-with-SPA-UI/files/5506794/localhost.zip)
To use `.har` file just extract archive and drag&drop it to your browser devtools

Also trying to migrate from 3.0 to 5.0 i am getting errors and api incompatibility problems

Can you please update this demo to latest version?

Thanks!

**Comment by sergeyshaykhullin** [comment]
No need, IS become paid =(

**Comment by PavelPikat** [comment]
> No need, IS become paid =(

That's not true, read their [license](https://github.com/IdentityServer/IdentityServer4/blob/main/LICENSE)

**Comment by sergeyshaykhullin** [comment]
IS4 is last apache licenced version with EOL November 2022

https://identityserver4.readthedocs.io/en/latest/
https://duendesoftware.com/

**Comment by PavelPikat** [comment]
> IS4 is last apache licenced version with EOL November 2022
> 
> https://identityserver4.readthedocs.io/en/latest/
> https://duendesoftware.com/

You can always fork it and continue using it. I'm sure OSS community will pick it up after 2022 as well.
